Changes needed for future rstan
nlmixrdevelopment/RxODE pull request #460
Opened 2021-09-24 06:18 UTC by andrjohns

Hi,

This PR adds the changes to compiler and linker flags needed for the upcoming version of rstan/StanHeaders. All that was needed in this case was adding the RcppParallel include files and linker flags.

Let me know if you need any more info.

Thanks!
Andrew

2021-09-24 13:40 UTC, mattfidler commented
Thanks @andrjohns 

Running other checks.  It is likely just fine

2021-09-24 13:46 UTC, mattfidler commented
Somehow this fails.

2021-09-24 13:49 UTC, mattfidler commented
I am re-running the base to see if it still works

2021-09-24 13:52 UTC, mattfidler requested changes

2021-09-24 13:52 UTC, mattfidler commented on inst/tools/workaround.R
> -.in <- gsub("@SL@", "", ##paste(capture.output(StanHeaders:::LdFlags()), capture.output(RcppParallel:::RcppParallelLibs())),
@andrjohns 

Maybe try commenting this out again.  The main branch seems to be working OK.

2021-09-24 14:31 UTC, andrjohns commented
Sorry about that, I updated the call to `StanHeaders:::LdFlags()` to satisfy Codefactor but it caused a different error. I've submitted the fix now

2021-09-25 03:10 UTC, andrjohns commented
I've re-run these changes locally on Windows and I can't replicate the R CMD check error from the windows testing above, would you be able to test locally as well?

2021-09-25 11:43 UTC, andrjohns commented
Apologies that this has been such a process. I was able to replicate the failure, it was caused by Windows linking against the wrong architecture for `RcppParallel` (i.e., was trying to link to 64-bit during 32-bit compilation)

2021-10-10 04:03 UTC, closed without merging